### ISSUE TITLE
The monthly report shows that no review is required

### ISSUE THREAD

**Issue by wenre** [NPW-Project/NPW_Mobile#2]
The monthly report shows that no review is required,Auditing is a waste of time

**Comment by wenre** [comment]
Does the npw roadmap need to be updated?

**Comment by wenre** [comment]
The advertising data that can be referenced in the advertising background is not comprehensive enough.

**Comment by normanx** [comment]
Monthly report says "Opened the advertising platform registration review mechanism", only register on open platform won't need review, publish Ads still need review, and review Ad mechanism won't be cancel any time.
If you have any suggestion to Ad backend platform, please feel free to tell us, we will try to implement good ideas to it.
